---
# defaults file for common

project_path: "{{ playbook_dir | dirname }}/{{ project }}"

unwanted_gitkeep_parent_dirs:
  - docs
  - roles/common/files
  - roles/common/templates
  - tests
  - tmp
  - utils
