---
# defaults file for pre_roles/common

date_cmd: "date +'%Y-%m-%d %H:%M:%S'"
start_stats:
  data:
    play: "{{ ansible_play_name }}"
    project: "{{ project | default('UNDEFINED') }}"
    playbook_dir: "{{ playbook_dir }}"
    status: 0
    start: "{{ lookup('pipe', '{{ date_cmd }}') }}"
