---
- name: <pr_r_common_t_common> be failed when the os not supported
  fail:
    msg: "The operating system is not supported!"
  vars:
    supported_os_distro:
      - CentOS
      - Fedora
      - RedHat
      - Ubuntu
  when: ansible_facts['distribution'] not in supported_os_distro

- name: <pr_r_common_t_common> set start stats
  set_stats:
    data: "{{ start_stats }}" # required. A dictionary of which each key represents a stat (or variable) you want to keep track of
    aggregate: true # not required. boolean that indicates if the provided value is aggregated to the existing stat C(yes) or will replace it C(no)
    per_host: true # not required. boolean that indicates if the stats is per host or for all hosts in the run.
